questions = [
    # General Knowledge
    {"question": "What is the capital of France?",
     "options": ["Berlin", "Rome", "Paris", "Madrid"],
     "answer": "Paris"},
    {"question": "Who painted the Mona Lisa?",
     "options": ["Michelangelo", "Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso"],
     "answer": "Leonardo da Vinci"},
    {"question": "What is the largest planet in our solar system?",
     "options": ["Earth", "Mars", "Jupiter", "Saturn"],
     "answer": "Jupiter"},
    {"question": "What is the chemical symbol for gold?",
     "options": ["Ag", "Au", "Fe", "Cu"],
     "answer": "Au"},
    {"question": "Who was the first president of the United States?",
     "options": ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"],
     "answer": "George Washington"},
    {"question": "What is the tallest mammal on Earth?",
     "options": ["Giraffe", "Elephant", "Gorilla", "Zebra"],
     "answer": "Giraffe"},
    {"question": "Which ocean is the largest?",
     "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
     "answer": "Pacific Ocean"},
    {"question": "What is the currency of Japan?",
     "options": ["Yuan", "Yen", "Rupee", "Dollar"],
     "answer": "Yen"},
    {"question": "Who wrote the play 'Romeo and Juliet'?",
     "options": ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
     "answer": "William Shakespeare"},
    {"question": "What is the chemical formula for water?",
     "options": ["CO2", "H2O", "NaCl", "O2"],
     "answer": "H2O"},

    # Science
    {"question": "What is the process by which plants make their own food?",
     "options": ["Respiration", "Photosynthesis", "Digestion", "Transpiration"],
     "answer": "Photosynthesis"},
    {"question": "What are the building blocks of proteins?",
     "options": ["Amino acids", "Carbohydrates", "Lipids", "Nucleic acids"],
     "answer": "Amino acids"},
    {"question": "What is the force that pulls objects towards the Earth?",
     "options": ["Friction", "Gravity", "Magnetism", "Electricity"],
     "answer": "Gravity"},
    {"question": "What is the smallest unit of matter?",
     "options": ["Atom", "Molecule", "Cell", "Organelle"],
     "answer": "Atom"},
    {"question": "Which layer of the Earth's atmosphere contains the ozone layer?",
     "options": ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"],
     "answer": "Stratosphere"},
    {"question": "What is the scientific name for humans?",
     "options": ["Homo sapiens", "Pan troglodytes", "Canis lupus", "Felis catus"],
     "answer": "Homo sapiens"},
    {"question": "What is DNA?",
     "options": ["A type of sugar", "A type of fat", "Deoxyribonucleic acid", "A type of protein"],
     "answer": "Deoxyribonucleic acid"},
    {"question": "What is the process by which a caterpillar turns into a butterfly?",
     "options": ["Metamorphosis", "Mitosis", "Meiosis", "Fermentation"],
     "answer": "Metamorphosis"},
    {"question": "What is the unit of electrical current?",
     "options": ["Volt", "Ampere", "Watt", "Ohm"],
     "answer": "Ampere"},
    {"question": "What is the speed of light?",
     "options": ["300,000 km/s", "3,000,000 km/s", "30,000,000 km/s", "3,000,000,000 km/s"],
     "answer": "300,000 km/s"},

    # History
    {"question": "When did World War II begin?",
     "options": ["1914", "1939", "1945", "1918"],
     "answer": "1939"},
    {"question": "Who was the first president of India?",
     "options": ["Mahatma Gandhi", "Jawaharlal Nehru", "Indira Gandhi", "Rajendra Prasad"],
     "answer": "Rajendra Prasad"},
    {"question": "What was the Great Wall of China built to protect against?",
     "options": ["Romans", "Mongols", "Greeks", "Egyptians"],
     "answer": "Mongols"},
    {"question": "The ancient Egyptians built the pyramids. What were they used for?",
     "options": ["Temples", "Homes", "Tombs", "Fortresses"],
     "answer": "Tombs"},
    {"question": "Who discovered America?",
     "options": ["Christopher Columbus", "Vasco da Gama", "Marco Polo", "Ferdinand Magellan"],
     "answer": "Christopher Columbus"},
    {"question": "The Renaissance was a period of great cultural and artistic achievement. When did it occur?",
     "options": ["14th-17th centuries", "10th-13th centuries", "5th-8th centuries", "1st-4th centuries"],
     "answer": "14th-17th centuries"},
    {"question": "The Industrial Revolution began in which country?",
     "options": ["France", "Germany", "Great Britain", "United States"],
     "answer": "Great Britain"},
    {"question": "Who wrote the Declaration of Independence?",
     "options": ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "Benjamin Franklin"],
     "answer": "Thomas Jefferson"},
    {"question": "The Roman Empire was centered around which city?",
     "options": ["Athens", "Rome", "Constantinople", "Alexandria"],
     "answer": "Rome"},
    {"question": "Who invented the printing press?",
     "options": ["Johannes Gutenberg", "Leonardo da Vinci", "Isaac Newton", "Albert Einstein"],
     "answer": "Johannes Gutenberg"},

    # Literature
    {"question": "Who wrote the novel 'Pride and Prejudice'?",
     "options": ["Jane Austen", "Emily Brontë", "Charlotte Brontë", "Virginia Woolf"],
     "answer": "Jane Austen"},
    {"question": "Which famous detective was created by Sir Arthur Conan Doyle?",
     "options": ["Sherlock Holmes", "Hercule Poirot", "Miss Marple", "Philip Marlowe"],
     "answer": "Sherlock Holmes"},
    {"question": "Who wrote the epic poem 'The Odyssey'?",
     "options": ["Homer", "Virgil", "Dante", "Shakespeare"],
     "answer": "Homer"},
    {"question": "What is the name of the magical world created by J.K. Rowling?",
     "options": ["Narnia", "Middle-earth", "Hogwarts", "Wonderland"],
     "answer": "Hogwarts"},
    {"question": "Who wrote the play 'Hamlet'?",
     "options": ["William Shakespeare", "Christopher Marlowe", "George Bernard Shaw", "Oscar Wilde"],
     "answer": "William Shakespeare"},
    {"question": "What is the name of the literary device where human characteristics are given to non-human things?",
     "options": ["Metaphor", "Simile", "Personification", "Onomatopoeia"],
     "answer": "Personification"},
    {"question": "Who wrote the novel 'To Kill a Mockingbird'?",
     "options": ["Harper Lee", "Ernest Hemingway", "F. Scott Fitzgerald", "Mark Twain"],
     "answer": "Harper Lee"},
    {"question": "What is the name of the genre of literature that tells stories about imaginary worlds and creatures?",
     "options": ["Romance", "Mystery", "Fantasy", "Science fiction"],
     "answer": "Fantasy"},
    {"question": "Who wrote the novel 'The Lord of the Rings'?",
     "options": ["J.R.R. Tolkien", "C.S. Lewis", "George Orwell", "J.K. Rowling"],
     "answer": "J.R.R. Tolkien"},
    {"question": "What is the name of a long narrative poem that tells a story of heroic deeds?",
     "options": ["Sonnet", "Haiku", "Epic", "Ballad"],
     "answer": "Epic"},

    # Geography
    {"question": "What is the highest mountain in the world?",
     "options": ["Mount Kilimanjaro", "Mount Everest", "Mount Fuji", "Mount McKinley"],
     "answer": "Mount Everest"},
    {"question": "Which continent is the largest?",
     "options": ["Africa", "Asia", "North America", "South America"],
     "answer": "Asia"},
    {"question": "What is the longest river in the world?",
     "options": ["Amazon", "Nile", "Yangtze", "Mississippi"],
     "answer": "Nile"},
    {"question": "What is the largest desert in the world?",
     "options": ["Sahara", "Gobi", "Arabian", "Antarctic"],
     "answer": "Antarctic"},
    {"question": "What is the capital of Australia?",
     "options": ["Sydney", "Melbourne", "Canberra", "Brisbane"],
     "answer": "Canberra"},
    {"question": "Which country is known for its canals?",
     "options": ["France", "Italy", "Netherlands", "Spain"],
     "answer": "Netherlands"},
    {"question": "What is the name of the Earth's outermost solid layer?",
     "options": ["Crust", "Mantle", "Core", "Lithosphere"],
     "answer": "Crust"},
    {"question": "What is the process by which water changes from liquid to gas?",
     "options": ["Condensation", "Evaporation", "Precipitation", "Sublimation"],
     "answer": "Evaporation"},
    {"question": "What are the major types of landforms?",
     "options": ["Mountains, valleys, plains, plateaus"],
     "answer": ["Mountains, valleys, plains, plateaus"]},
    {"question": "What is the study of weather and climate?",
     "options": ["Meteorology", "Geology", "Oceanography", "Astronomy"],
     "answer": "Meteorology"},


]